version: '3'

services:
    php:
        build:
            context: .
        image: php:8.1-cli
        container_name: coupling_detector
        volumes:
            - ./:/opt/app
        working_dir: /opt/app
