services:
    php:
        build:
            context: .
        container_name: coupling_detector
        volumes:
            - ./:/opt/app
            - '${HOST_COMPOSER_CACHE_DIR:-~/.cache/composer}:/home/composer/.cache/composer'
            - '${HOST_COMPOSER_HOME:-~/.config/composer}:/home/composer/.config/composer'
        working_dir: /opt/app
