name: Akeneo Coupling Detector CI
on: [push]
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Setup PHP with no coverage driver
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Check PHP version
              run: php -v

            - name: Vendor
              run: composer install

            - name: Specs
              run: ./vendor/bin/phpspec run

            - name: Static tests
              run: ./vendor/bin/phpstan analyse src -l 5
